apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        aadpodidbinding: catalog
    spec:
      containers:
      - name: catalog
        image: dotneteconomy.azurecr.io/dotnet.catalog:1.0.4
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: dotneteconomy
          - name: ServiceSettings__Authority
            value: https://dotneteconomy.eastus.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            port: 5000
            path: /health/live
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            port: 5000
            path: /health/ready
          initialDelaySeconds: 10
        
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: ClusterIP #Default type for Kubernetes
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 5000
